#!/bin/bash
echo "🌟 Pharbit Blockchain - GitHub Codespaces Status"
echo "==============================================="
echo "📍 Environment: GitHub Codespaces"
echo "🖥️  Machine: $(uname -a)"
echo "🌐 Codespace: $CODESPACE_NAME"
echo ""
echo "📊 Development Stack:"
echo "  Node.js: $(node --version)"
echo "  NPM: $(npm --version)"
echo "  Hardhat: $(npx hardhat --version 2>/dev/null || echo 'Not found')"
echo ""
echo "🔑 Environment Variables:"
env | grep -E "(ALCHEMY|INFURA|PHARBIT)" | cut -d= -f1 | sed 's/^/  ✅ /'
echo ""
echo "🌐 Forwarded Ports:"
echo "  3000 - Blockchain API"
echo "  3001 - Frontend Development"  
echo "  8545 - Ethereum RPC"
echo ""
echo "🚀 Quick Start Commands:"
echo "  pharbit-start           - Start blockchain system"
echo "  blockchain-test         - Test blockchain"
echo "  contracts-compile       - Compile smart contracts"
echo "  ganache                 - Start local Ethereum"
